-- Apply with `supabase db push` (or paste into the Supabase SQL editor) before
-- deploying. Tables are private: the browser must only access approved views/RPCs.
create table if not exists patterns_detected (
  id bigint generated by default as identity primary key, timestamp timestamptz,
  pattern_name text, signal_type text, confidence double precision, ml_confidence double precision,
  combined_confidence double precision, price_detection double precision, position_size double precision,
  prediction text, timeframe text, status text default 'open', result text, profit_loss double precision,
  duration_minutes integer, exit_reason text, created_at timestamptz default now()
);
create table if not exists price_history (
  id bigint generated by default as identity primary key, timestamp timestamptz not null, symbol text not null,
  timeframe text not null, open double precision, high double precision, low double precision, close double precision,
  volume double precision, created_at timestamptz default now(), unique(timestamp, symbol, timeframe)
);
create table if not exists performance_metrics (
  id bigint generated by default as identity primary key, timestamp timestamptz, total_patterns integer, success_rate double precision,
  avg_profit_loss double precision, total_return double precision, sharpe_ratio double precision, max_drawdown double precision
);
create table if not exists news_sentiment (
  id bigint generated by default as identity primary key, timestamp timestamptz, score double precision, label text, confidence double precision,
  news_count integer, positive_count integer, negative_count integer, neutral_count integer, created_at timestamptz default now()
);
create table if not exists news_articles (
  id bigint generated by default as identity primary key, timestamp timestamptz, title text, source text, sentiment_score double precision,
  sentiment_label text, url text unique, created_at timestamptz default now()
);
create table if not exists ml_recipe_runs (
  id bigint generated by default as identity primary key, recipe_hash text unique, symbol text, timeframe text, horizon text,
  config_json jsonb, total_predictions integer, accuracy double precision, created_at timestamptz default now()
);
create table if not exists ml_recipe_predictions (
  id bigint generated by default as identity primary key, run_id bigint references ml_recipe_runs(id), timestamp timestamptz,
  predicted_direction text, actual_direction text, confidence double precision, was_correct boolean, decision_hash text, created_at timestamptz default now()
);
create index if not exists idx_ml_recipe_predictions_run_id on ml_recipe_predictions(run_id);
create table if not exists collected_signals (
  id bigint generated by default as identity primary key, timestamp timestamptz not null, pattern text not null, confidence double precision,
  signal text not null, price double precision, market_data jsonb, created_at timestamptz default now(), unique(timestamp,pattern,signal)
);
create table if not exists open_interest (
  id bigint generated by default as identity primary key, timestamp timestamptz, symbol text, timeframe text, oi_current double precision,
  oi_long double precision, oi_short double precision, oi_ratio double precision, change_percent double precision, created_at timestamptz default now()
);
create table if not exists funding_rates (
  id bigint generated by default as identity primary key, timestamp timestamptz, symbol text, funding_rate double precision,
  mark_price double precision, index_price double precision, estimated_settle_time bigint, created_at timestamptz default now()
);
create table if not exists liquidations (id bigint generated by default as identity primary key, timestamp timestamptz, symbol text, side text, price double precision, quantity double precision, usd_value double precision, created_at timestamptz default now());
create table if not exists exchange_flow (id bigint generated by default as identity primary key, timestamp timestamptz, symbol text, exchange text, direction text, quantity double precision, usd_value double precision, created_at timestamptz default now());
create table if not exists implied_volatility (id bigint generated by default as identity primary key, timestamp timestamptz, symbol text, iv_rank double precision, iv_percentile double precision, volatility double precision, source text, created_at timestamptz default now());
create table if not exists market_dominance (id bigint generated by default as identity primary key, timestamp timestamptz, btc_dominance double precision, eth_dominance double precision, altcoin_dominance double precision, created_at timestamptz default now());
create table if not exists predictions (
  id bigint generated by default as identity primary key, timestamp timestamptz, timeframe text, prediction_type text, predicted_direction text,
  target_price double precision, confidence double precision, model_type text, features_used jsonb, sentiment_score double precision,
  oi_ratio double precision, funding_rate double precision, additional_context jsonb, actual_direction text, actual_price double precision,
  was_correct boolean, profit_loss double precision, error_percent double precision, created_at timestamptz default now(), resolved_at timestamptz
);
create table if not exists historical_events (id bigint generated by default as identity primary key, date timestamptz, event_name text, category text, description text, price_before double precision, price_1h_after double precision, price_24h_after double precision, price_7d_after double precision, volatility_change double precision, created_at timestamptz default now());
create table if not exists whale_activity (id bigint generated by default as identity primary key, timestamp timestamptz, address text, transaction_hash text, direction text, quantity double precision, usd_value double precision, from_exchange boolean, to_exchange boolean, created_at timestamptz default now());
create table if not exists order_book_snapshot (id bigint generated by default as identity primary key, timestamp timestamptz, symbol text, bid_price double precision, bid_size double precision, ask_price double precision, ask_size double precision, bid_ask_ratio double precision, total_bid_volume double precision, total_ask_volume double precision, created_at timestamptz default now());
create table if not exists macro_correlations (id bigint generated by default as identity primary key, timestamp timestamptz, btc_close double precision, gold_close double precision, sp500_close double precision, dxy_close double precision, vix_close double precision, yield_10y double precision, yield_2y double precision, correlation_gold double precision, correlation_sp500 double precision, correlation_dxy double precision, created_at timestamptz default now());

-- Durable orchestration and human-in-the-loop trading.
create table if not exists analysis_runs (
  id bigint generated by default as identity primary key, trigger_message_id text, status text not null,
  summary jsonb, error text, created_at timestamptz default now(), finished_at timestamptz
);
create table if not exists trade_suggestions (
  id bigint generated by default as identity primary key, dedupe_key text unique not null, symbol text not null,
  pattern text not null, confidence double precision not null, entry_price double precision not null,
  position_size double precision not null, quantity double precision not null, stop_loss double precision not null,
  take_profit double precision not null, status text not null default 'pending' check (status in ('pending','approval_in_progress','approved','expired','rejected')),
  context jsonb not null default '{}'::jsonb, execution_error text, created_at timestamptz default now(),
  expires_at timestamptz default now() + interval '2 hours', approved_at timestamptz, approved_by text
);
create table if not exists positions (
  id bigint generated by default as identity primary key, suggestion_id bigint unique not null references trade_suggestions(id),
  symbol text not null, pattern text not null, entry_price double precision not null, quantity double precision not null,
  position_size double precision not null, stop_loss double precision not null, take_profit double precision not null,
  status text not null default 'open' check (status in ('open','closing','closed')), buy_order_id text not null, sell_order_id text,
  exit_price double precision, profit_loss double precision, exit_reason text, approved_by text not null,
  created_at timestamptz default now(), closed_at timestamptz
);
create index if not exists idx_positions_open on positions(status) where status='open';

-- The Python functions use DATABASE_URL with the service role/database password.
-- Browser access remains denied until the planned UI adds narrowly-scoped RLS policies/views.
alter table patterns_detected enable row level security;
alter table price_history enable row level security;
alter table performance_metrics enable row level security;
alter table news_sentiment enable row level security;
alter table news_articles enable row level security;
alter table ml_recipe_runs enable row level security;
alter table ml_recipe_predictions enable row level security;
alter table collected_signals enable row level security;
alter table open_interest enable row level security;
alter table funding_rates enable row level security;
alter table liquidations enable row level security;
alter table exchange_flow enable row level security;
alter table implied_volatility enable row level security;
alter table market_dominance enable row level security;
alter table predictions enable row level security;
alter table historical_events enable row level security;
alter table whale_activity enable row level security;
alter table order_book_snapshot enable row level security;
alter table macro_correlations enable row level security;
alter table analysis_runs enable row level security;
alter table trade_suggestions enable row level security;
alter table positions enable row level security;
