-- Audit trail for local model training and optional Vercel deployments.
create table if not exists model_training_runs (
  id bigint generated by default as identity primary key,
  version text not null unique,
  status text not null check (status in ('completed', 'failed', 'deployed')),
  data_start timestamptz,
  data_end timestamptz,
  total_rows integer not null default 0,
  metrics jsonb not null default '{}'::jsonb,
  model_sha256 text,
  scaler_sha256 text,
  backup_path text,
  deployment_url text,
  error text,
  created_at timestamptz not null default now(),
  deployed_at timestamptz
);
create index if not exists idx_model_training_runs_created_at on model_training_runs(created_at desc);
alter table model_training_runs enable row level security;
